namespace UI
{
    partial class FrmAnaDashboard
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            panelScroll = new Panel();
            pnlDecisions = new GroupBox();
            btnDecisionVer = new Button();
            lblDecision3 = new Label();
            lblDecision2 = new Label();
            lblDecision1 = new Label();
            pnlTrends = new GroupBox();
            pnlChartTrends = new Panel();
            lblChartTrends = new Label();
            cmbTrendMetric = new ComboBox();
            cmbTrendPeriod = new ComboBox();
            pnlProducts = new GroupBox();
            lstWatch = new ListBox();
            lstTop = new ListBox();
            lblWatchTitle = new Label();
            lblTopTitle = new Label();
            pnlCapital = new GroupBox();
            pnlChartCapital = new Panel();
            lblChartCapital = new Label();
            lblCapCaja = new Label();
            lblCapInventario = new Label();
            lblCapPendiente = new Label();
            lblCapRecuperado = new Label();
            lblCapInvertido = new Label();
            pnlProfitability = new GroupBox();
            lblGanPotencial = new Label();
            lblGanRealizada = new Label();
            lblProfitRoi = new Label();
            lblProfitMargen = new Label();
            lblProfitGanancia = new Label();
            pnlFrozenCapital = new GroupBox();
            btnVerDetalleCapital = new Button();
            progressFrozen = new ProgressBar();
            lblFrozenDias = new Label();
            lblFrozenProductos = new Label();
            lblFrozenPct = new Label();
            lblFrozenValor = new Label();
            pnlInventoryHealth = new GroupBox();
            lblHealthScore = new Label();
            lblHealthTitle = new Label();
            pnlCriticos = new Panel();
            lblCriticosVal = new Label();
            lblCriticosTitle = new Label();
            pnlLentos = new Panel();
            lblLentosVal = new Label();
            lblLentosTitle = new Label();
            pnlBuenos = new Panel();
            lblBuenosVal = new Label();
            lblBuenosTitle = new Label();
            pnlEstrella = new Panel();
            lblEstrellaVal = new Label();
            lblEstrellaTitle = new Label();
            pnlKPIs = new GroupBox();
            pnlKpiRoi = new Panel();
            lblKpiRoiDelta = new Label();
            lblKpiRoiVal = new Label();
            lblKpiRoiTitle = new Label();
            pnlKpiGanancia = new Panel();
            lblKpiGanDelta = new Label();
            lblKpiGanVal = new Label();
            lblKpiGanTitle = new Label();
            pnlKpiVentas = new Panel();
            lblKpiVenDelta = new Label();
            lblKpiVenVal = new Label();
            lblKpiVenTitle = new Label();
            pnlKpiInventario = new Panel();
            lblKpiInvDelta = new Label();
            lblKpiInvVal = new Label();
            lblKpiInvTitle = new Label();
            pnlKpiCapital = new Panel();
            lblKpiCapDelta = new Label();
            lblKpiCapVal = new Label();
            lblKpiCapTitle = new Label();
            panelScroll.SuspendLayout();
            pnlDecisions.SuspendLayout();
            pnlTrends.SuspendLayout();
            pnlChartTrends.SuspendLayout();
            pnlProducts.SuspendLayout();
            pnlCapital.SuspendLayout();
            pnlChartCapital.SuspendLayout();
            pnlProfitability.SuspendLayout();
            pnlFrozenCapital.SuspendLayout();
            pnlInventoryHealth.SuspendLayout();
            pnlCriticos.SuspendLayout();
            pnlLentos.SuspendLayout();
            pnlBuenos.SuspendLayout();
            pnlEstrella.SuspendLayout();
            pnlKPIs.SuspendLayout();
            pnlKpiRoi.SuspendLayout();
            pnlKpiGanancia.SuspendLayout();
            pnlKpiVentas.SuspendLayout();
            pnlKpiInventario.SuspendLayout();
            pnlKpiCapital.SuspendLayout();
            SuspendLayout();
            // panelScroll
            panelScroll.AutoScroll = true;
            panelScroll.BackColor = Color.FromArgb(247, 249, 252);
            panelScroll.Controls.Add(pnlDecisions);
            panelScroll.Controls.Add(pnlTrends);
            panelScroll.Controls.Add(pnlProducts);
            panelScroll.Controls.Add(pnlCapital);
            panelScroll.Controls.Add(pnlProfitability);
            panelScroll.Controls.Add(pnlFrozenCapital);
            panelScroll.Controls.Add(pnlInventoryHealth);
            panelScroll.Controls.Add(pnlKPIs);
            panelScroll.Dock = DockStyle.Fill;
            panelScroll.Location = new Point(0, 0);
            panelScroll.Name = "panelScroll";
            panelScroll.Padding = new Padding(12);
            panelScroll.Size = new Size(1000, 700);
            panelScroll.TabIndex = 0;
            // pnlKPIs
            pnlKPIs.Controls.Add(pnlKpiRoi);
            pnlKPIs.Controls.Add(pnlKpiGanancia);
            pnlKPIs.Controls.Add(pnlKpiVentas);
            pnlKPIs.Controls.Add(pnlKpiInventario);
            pnlKPIs.Controls.Add(pnlKpiCapital);
            pnlKPIs.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlKPIs.Location = new Point(16, 12);
            pnlKPIs.Name = "pnlKPIs";
            pnlKPIs.Size = new Size(940, 150);
            pnlKPIs.TabIndex = 0;
            pnlKPIs.TabStop = false;
            pnlKPIs.Text = "KPIs";
            pnlKPIs.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            // KPI cards
            ConfigureKpiCard(pnlKpiCapital, lblKpiCapTitle, lblKpiCapVal, lblKpiCapDelta, new Point(16, 28), "CAPITAL", "RD$250,000", "+12.5%");
            ConfigureKpiCard(pnlKpiInventario, lblKpiInvTitle, lblKpiInvVal, lblKpiInvDelta, new Point(200, 28), "INVENTARIO", "RD$95,000", "38% CAPITAL");
            ConfigureKpiCard(pnlKpiVentas, lblKpiVenTitle, lblKpiVenVal, lblKpiVenDelta, new Point(384, 28), "VENTAS", "RD$180,000", "+9.1%");
            ConfigureKpiCard(pnlKpiGanancia, lblKpiGanTitle, lblKpiGanVal, lblKpiGanDelta, new Point(568, 28), "GANANCIA", "RD$52,000", "+18.4%");
            ConfigureKpiCard(pnlKpiRoi, lblKpiRoiTitle, lblKpiRoiVal, lblKpiRoiDelta, new Point(752, 28), "ROI", "43.7%", "+6.2%");
            // Inventory health
            pnlInventoryHealth.Controls.Add(lblHealthScore);
            pnlInventoryHealth.Controls.Add(lblHealthTitle);
            pnlInventoryHealth.Controls.Add(pnlCriticos);
            pnlInventoryHealth.Controls.Add(pnlLentos);
            pnlInventoryHealth.Controls.Add(pnlBuenos);
            pnlInventoryHealth.Controls.Add(pnlEstrella);
            pnlInventoryHealth.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlInventoryHealth.Location = new Point(16, 176);
            pnlInventoryHealth.Name = "pnlInventoryHealth";
            pnlInventoryHealth.Size = new Size(940, 170);
            pnlInventoryHealth.TabIndex = 1;
            pnlInventoryHealth.TabStop = false;
            pnlInventoryHealth.Text = "Estado del inventario";
            pnlInventoryHealth.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            ConfigureStatusCard(pnlEstrella, lblEstrellaTitle, lblEstrellaVal, new Point(16, 28), "ESTRELLA", "7");
            ConfigureStatusCard(pnlBuenos, lblBuenosTitle, lblBuenosVal, new Point(170, 28), "BUEN REND.", "18");
            ConfigureStatusCard(pnlLentos, lblLentosTitle, lblLentosVal, new Point(324, 28), "LENTOS", "9");
            ConfigureStatusCard(pnlCriticos, lblCriticosTitle, lblCriticosVal, new Point(478, 28), "CRITICOS", "4");
            lblHealthTitle.AutoSize = true;
            lblHealthTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblHealthTitle.Location = new Point(650, 40);
            lblHealthTitle.Name = "lblHealthTitle";
            lblHealthTitle.Size = new Size(160, 20);
            lblHealthTitle.TabIndex = 4;
            lblHealthTitle.Text = "SALUD DEL INVENTARIO";
            lblHealthScore.AutoSize = true;
            lblHealthScore.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
            lblHealthScore.ForeColor = Color.FromArgb(56, 161, 105);
            lblHealthScore.Location = new Point(660, 72);
            lblHealthScore.Name = "lblHealthScore";
            lblHealthScore.Size = new Size(140, 50);
            lblHealthScore.TabIndex = 5;
            lblHealthScore.Text = "78 / 100";
            // Frozen capital
            pnlFrozenCapital.Controls.Add(btnVerDetalleCapital);
            pnlFrozenCapital.Controls.Add(progressFrozen);
            pnlFrozenCapital.Controls.Add(lblFrozenDias);
            pnlFrozenCapital.Controls.Add(lblFrozenProductos);
            pnlFrozenCapital.Controls.Add(lblFrozenPct);
            pnlFrozenCapital.Controls.Add(lblFrozenValor);
            pnlFrozenCapital.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlFrozenCapital.Location = new Point(16, 360);
            pnlFrozenCapital.Name = "pnlFrozenCapital";
            pnlFrozenCapital.Size = new Size(940, 130);
            pnlFrozenCapital.TabIndex = 2;
            pnlFrozenCapital.TabStop = false;
            pnlFrozenCapital.Text = "Capital congelado";
            pnlFrozenCapital.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblFrozenValor.AutoSize = true;
            lblFrozenValor.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblFrozenValor.Location = new Point(20, 32);
            lblFrozenValor.Name = "lblFrozenValor";
            lblFrozenValor.Size = new Size(160, 41);
            lblFrozenValor.TabIndex = 0;
            lblFrozenValor.Text = "RD$31,500";
            lblFrozenPct.AutoSize = true;
            lblFrozenPct.Font = new Font("Segoe UI", 9F);
            lblFrozenPct.ForeColor = Color.FromArgb(113, 128, 150);
            lblFrozenPct.Location = new Point(24, 76);
            lblFrozenPct.Name = "lblFrozenPct";
            lblFrozenPct.Size = new Size(220, 20);
            lblFrozenPct.TabIndex = 1;
            lblFrozenPct.Text = "26.25% del capital invertido";
            lblFrozenProductos.AutoSize = true;
            lblFrozenProductos.Font = new Font("Segoe UI", 9F);
            lblFrozenProductos.Location = new Point(280, 40);
            lblFrozenProductos.Name = "lblFrozenProductos";
            lblFrozenProductos.Size = new Size(100, 20);
            lblFrozenProductos.TabIndex = 2;
            lblFrozenProductos.Text = "13 productos";
            lblFrozenDias.AutoSize = true;
            lblFrozenDias.Font = new Font("Segoe UI", 9F);
            lblFrozenDias.Location = new Point(280, 68);
            lblFrozenDias.Name = "lblFrozenDias";
            lblFrozenDias.Size = new Size(140, 20);
            lblFrozenDias.TabIndex = 3;
            lblFrozenDias.Text = "64 dias promedio";
            progressFrozen.Location = new Point(450, 48);
            progressFrozen.Name = "progressFrozen";
            progressFrozen.Size = new Size(280, 24);
            progressFrozen.TabIndex = 4;
            progressFrozen.Value = 62;
            btnVerDetalleCapital.Enabled = false;
            btnVerDetalleCapital.Location = new Point(760, 44);
            btnVerDetalleCapital.Name = "btnVerDetalleCapital";
            btnVerDetalleCapital.Size = new Size(150, 32);
            btnVerDetalleCapital.TabIndex = 5;
            btnVerDetalleCapital.Text = "VER DETALLE";
            btnVerDetalleCapital.UseVisualStyleBackColor = true;
            // Profitability
            pnlProfitability.Controls.Add(lblGanPotencial);
            pnlProfitability.Controls.Add(lblGanRealizada);
            pnlProfitability.Controls.Add(lblProfitRoi);
            pnlProfitability.Controls.Add(lblProfitMargen);
            pnlProfitability.Controls.Add(lblProfitGanancia);
            pnlProfitability.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlProfitability.Location = new Point(16, 504);
            pnlProfitability.Name = "pnlProfitability";
            pnlProfitability.Size = new Size(460, 160);
            pnlProfitability.TabIndex = 3;
            pnlProfitability.TabStop = false;
            pnlProfitability.Text = "Rentabilidad";
            lblProfitGanancia.AutoSize = true;
            lblProfitGanancia.Font = new Font("Segoe UI", 9F);
            lblProfitGanancia.Location = new Point(20, 36);
            lblProfitGanancia.Name = "lblProfitGanancia";
            lblProfitGanancia.Size = new Size(180, 20);
            lblProfitGanancia.TabIndex = 0;
            lblProfitGanancia.Text = "Ganancia: RD$52,000";
            lblProfitMargen.AutoSize = true;
            lblProfitMargen.Font = new Font("Segoe UI", 9F);
            lblProfitMargen.Location = new Point(20, 62);
            lblProfitMargen.Name = "lblProfitMargen";
            lblProfitMargen.Size = new Size(120, 20);
            lblProfitMargen.TabIndex = 1;
            lblProfitMargen.Text = "Margen: 28.9%";
            lblProfitRoi.AutoSize = true;
            lblProfitRoi.Font = new Font("Segoe UI", 9F);
            lblProfitRoi.Location = new Point(20, 88);
            lblProfitRoi.Name = "lblProfitRoi";
            lblProfitRoi.Size = new Size(100, 20);
            lblProfitRoi.TabIndex = 2;
            lblProfitRoi.Text = "ROI: 43.7%";
            lblGanRealizada.AutoSize = true;
            lblGanRealizada.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblGanRealizada.ForeColor = Color.FromArgb(56, 161, 105);
            lblGanRealizada.Location = new Point(220, 48);
            lblGanRealizada.Name = "lblGanRealizada";
            lblGanRealizada.Size = new Size(200, 20);
            lblGanRealizada.TabIndex = 3;
            lblGanRealizada.Text = "GANANCIA REALIZADA";
            lblGanPotencial.AutoSize = true;
            lblGanPotencial.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblGanPotencial.ForeColor = Color.FromArgb(49, 130, 206);
            lblGanPotencial.Location = new Point(220, 84);
            lblGanPotencial.Name = "lblGanPotencial";
            lblGanPotencial.Size = new Size(200, 20);
            lblGanPotencial.TabIndex = 4;
            lblGanPotencial.Text = "GANANCIA POTENCIAL";
            // Capital
            pnlCapital.Controls.Add(pnlChartCapital);
            pnlCapital.Controls.Add(lblCapCaja);
            pnlCapital.Controls.Add(lblCapInventario);
            pnlCapital.Controls.Add(lblCapPendiente);
            pnlCapital.Controls.Add(lblCapRecuperado);
            pnlCapital.Controls.Add(lblCapInvertido);
            pnlCapital.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlCapital.Location = new Point(496, 504);
            pnlCapital.Name = "pnlCapital";
            pnlCapital.Size = new Size(460, 160);
            pnlCapital.TabIndex = 4;
            pnlCapital.TabStop = false;
            pnlCapital.Text = "Capital";
            lblCapInvertido.AutoSize = true;
            lblCapInvertido.Font = new Font("Segoe UI", 8.5F);
            lblCapInvertido.Location = new Point(16, 32);
            lblCapInvertido.Name = "lblCapInvertido";
            lblCapInvertido.Size = new Size(180, 19);
            lblCapInvertido.TabIndex = 0;
            lblCapInvertido.Text = "Invertido: RD$120,000";
            lblCapRecuperado.AutoSize = true;
            lblCapRecuperado.Font = new Font("Segoe UI", 8.5F);
            lblCapRecuperado.Location = new Point(16, 54);
            lblCapRecuperado.Name = "lblCapRecuperado";
            lblCapRecuperado.Size = new Size(180, 19);
            lblCapRecuperado.TabIndex = 1;
            lblCapRecuperado.Text = "Recuperado: RD$88,500";
            lblCapPendiente.AutoSize = true;
            lblCapPendiente.Font = new Font("Segoe UI", 8.5F);
            lblCapPendiente.Location = new Point(16, 76);
            lblCapPendiente.Name = "lblCapPendiente";
            lblCapPendiente.Size = new Size(180, 19);
            lblCapPendiente.TabIndex = 2;
            lblCapPendiente.Text = "Pendiente: RD$31,500";
            lblCapInventario.AutoSize = true;
            lblCapInventario.Font = new Font("Segoe UI", 8.5F);
            lblCapInventario.Location = new Point(16, 98);
            lblCapInventario.Name = "lblCapInventario";
            lblCapInventario.Size = new Size(180, 19);
            lblCapInventario.TabIndex = 3;
            lblCapInventario.Text = "En inventario: RD$95,000";
            lblCapCaja.AutoSize = true;
            lblCapCaja.Font = new Font("Segoe UI", 8.5F);
            lblCapCaja.Location = new Point(16, 120);
            lblCapCaja.Name = "lblCapCaja";
            lblCapCaja.Size = new Size(160, 19);
            lblCapCaja.TabIndex = 4;
            lblCapCaja.Text = "En caja: RD$42,000";
            pnlChartCapital.BackColor = Color.FromArgb(237, 242, 247);
            pnlChartCapital.BorderStyle = BorderStyle.FixedSingle;
            pnlChartCapital.Controls.Add(lblChartCapital);
            pnlChartCapital.Location = new Point(230, 32);
            pnlChartCapital.Name = "pnlChartCapital";
            pnlChartCapital.Size = new Size(210, 110);
            pnlChartCapital.TabIndex = 5;
            lblChartCapital.Dock = DockStyle.Fill;
            lblChartCapital.Font = new Font("Segoe UI", 9F);
            lblChartCapital.ForeColor = Color.FromArgb(113, 128, 150);
            lblChartCapital.Location = new Point(0, 0);
            lblChartCapital.Name = "lblChartCapital";
            lblChartCapital.Size = new Size(208, 108);
            lblChartCapital.TabIndex = 0;
            lblChartCapital.Text = "Distribucion del capital\r\n(placeholder grafico)";
            lblChartCapital.TextAlign = ContentAlignment.MiddleCenter;
            // Products
            pnlProducts.Controls.Add(lstWatch);
            pnlProducts.Controls.Add(lstTop);
            pnlProducts.Controls.Add(lblWatchTitle);
            pnlProducts.Controls.Add(lblTopTitle);
            pnlProducts.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlProducts.Location = new Point(16, 680);
            pnlProducts.Name = "pnlProducts";
            pnlProducts.Size = new Size(460, 200);
            pnlProducts.TabIndex = 5;
            pnlProducts.TabStop = false;
            pnlProducts.Text = "Productos";
            lblTopTitle.AutoSize = true;
            lblTopTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblTopTitle.Location = new Point(16, 28);
            lblTopTitle.Name = "lblTopTitle";
            lblTopTitle.Size = new Size(120, 20);
            lblTopTitle.TabIndex = 0;
            lblTopTitle.Text = "TOP PRODUCTOS";
            lstTop.Font = new Font("Segoe UI", 9F);
            lstTop.FormattingEnabled = true;
            lstTop.ItemHeight = 20;
            lstTop.Items.AddRange(new object[] { "1. Proteina X", "2. Creatina X", "3. Shaker", "4. Producto X", "5. Producto Y" });
            lstTop.Location = new Point(16, 52);
            lstTop.Name = "lstTop";
            lstTop.Size = new Size(200, 124);
            lstTop.TabIndex = 1;
            lblWatchTitle.AutoSize = true;
            lblWatchTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblWatchTitle.Location = new Point(240, 28);
            lblWatchTitle.Name = "lblWatchTitle";
            lblWatchTitle.Size = new Size(160, 20);
            lblWatchTitle.TabIndex = 2;
            lblWatchTitle.Text = "PRODUCTOS A VIGILAR";
            lstWatch.Font = new Font("Segoe UI", 9F);
            lstWatch.FormattingEnabled = true;
            lstWatch.ItemHeight = 20;
            lstWatch.Items.AddRange(new object[] { "Camiseta X", "Producto Y", "Producto Z" });
            lstWatch.Location = new Point(240, 52);
            lstWatch.Name = "lstWatch";
            lstWatch.Size = new Size(200, 124);
            lstWatch.TabIndex = 3;
            // Trends
            pnlTrends.Controls.Add(pnlChartTrends);
            pnlTrends.Controls.Add(cmbTrendPeriod);
            pnlTrends.Controls.Add(cmbTrendMetric);
            pnlTrends.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlTrends.Location = new Point(496, 680);
            pnlTrends.Name = "pnlTrends";
            pnlTrends.Size = new Size(460, 200);
            pnlTrends.TabIndex = 6;
            pnlTrends.TabStop = false;
            pnlTrends.Text = "Tendencias";
            cmbTrendMetric.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbTrendMetric.Enabled = false;
            cmbTrendMetric.Font = new Font("Segoe UI", 9F);
            cmbTrendMetric.FormattingEnabled = true;
            cmbTrendMetric.Items.AddRange(new object[] { "Ventas", "Ganancia", "ROI", "Margen", "Capital" });
            cmbTrendMetric.Location = new Point(16, 32);
            cmbTrendMetric.Name = "cmbTrendMetric";
            cmbTrendMetric.Size = new Size(140, 28);
            cmbTrendMetric.TabIndex = 0;
            cmbTrendPeriod.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbTrendPeriod.Enabled = false;
            cmbTrendPeriod.Font = new Font("Segoe UI", 9F);
            cmbTrendPeriod.FormattingEnabled = true;
            cmbTrendPeriod.Items.AddRange(new object[] { "Ultimos 12 meses", "Ultimos 6 meses", "Este anio" });
            cmbTrendPeriod.Location = new Point(170, 32);
            cmbTrendPeriod.Name = "cmbTrendPeriod";
            cmbTrendPeriod.Size = new Size(160, 28);
            cmbTrendPeriod.TabIndex = 1;
            pnlChartTrends.BackColor = Color.FromArgb(237, 242, 247);
            pnlChartTrends.BorderStyle = BorderStyle.FixedSingle;
            pnlChartTrends.Controls.Add(lblChartTrends);
            pnlChartTrends.Location = new Point(16, 72);
            pnlChartTrends.Name = "pnlChartTrends";
            pnlChartTrends.Size = new Size(424, 110);
            pnlChartTrends.TabIndex = 2;
            lblChartTrends.Dock = DockStyle.Fill;
            lblChartTrends.Font = new Font("Segoe UI", 9F);
            lblChartTrends.ForeColor = Color.FromArgb(113, 128, 150);
            lblChartTrends.Location = new Point(0, 0);
            lblChartTrends.Name = "lblChartTrends";
            lblChartTrends.Size = new Size(422, 108);
            lblChartTrends.TabIndex = 0;
            lblChartTrends.Text = "Area de grafico (placeholder visual)";
            lblChartTrends.TextAlign = ContentAlignment.MiddleCenter;
            // Decisions
            pnlDecisions.Controls.Add(btnDecisionVer);
            pnlDecisions.Controls.Add(lblDecision3);
            pnlDecisions.Controls.Add(lblDecision2);
            pnlDecisions.Controls.Add(lblDecision1);
            pnlDecisions.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            pnlDecisions.Location = new Point(16, 900);
            pnlDecisions.Name = "pnlDecisions";
            pnlDecisions.Size = new Size(940, 150);
            pnlDecisions.TabIndex = 7;
            pnlDecisions.TabStop = false;
            pnlDecisions.Text = "Centro de decisiones";
            pnlDecisions.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblDecision1.Font = new Font("Segoe UI", 9F);
            lblDecision1.Location = new Point(20, 32);
            lblDecision1.Name = "lblDecision1";
            lblDecision1.Size = new Size(700, 24);
            lblDecision1.TabIndex = 0;
            lblDecision1.Text = "REPOSICION — Proteina X necesita reposicion.";
            lblDecision2.Font = new Font("Segoe UI", 9F);
            lblDecision2.Location = new Point(20, 60);
            lblDecision2.Name = "lblDecision2";
            lblDecision2.Size = new Size(700, 24);
            lblDecision2.TabIndex = 1;
            lblDecision2.Text = "CAPITAL CONGELADO — RD$31,500 estan comprometidos.";
            lblDecision3.Font = new Font("Segoe UI", 9F);
            lblDecision3.Location = new Point(20, 88);
            lblDecision3.Name = "lblDecision3";
            lblDecision3.Size = new Size(700, 24);
            lblDecision3.TabIndex = 2;
            lblDecision3.Text = "RENTABILIDAD — El margen de un producto disminuyo.";
            btnDecisionVer.Enabled = false;
            btnDecisionVer.Location = new Point(760, 56);
            btnDecisionVer.Name = "btnDecisionVer";
            btnDecisionVer.Size = new Size(150, 32);
            btnDecisionVer.TabIndex = 3;
            btnDecisionVer.Text = "Ver / Analizar";
            btnDecisionVer.UseVisualStyleBackColor = true;
            // Form
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1000, 700);
            Controls.Add(panelScroll);
            FormBorderStyle = FormBorderStyle.None;
            Name = "FrmAnaDashboard";
            Text = "Dashboard";
            panelScroll.ResumeLayout(false);
            pnlDecisions.ResumeLayout(false);
            pnlTrends.ResumeLayout(false);
            pnlChartTrends.ResumeLayout(false);
            pnlProducts.ResumeLayout(false);
            pnlProducts.PerformLayout();
            pnlCapital.ResumeLayout(false);
            pnlCapital.PerformLayout();
            pnlChartCapital.ResumeLayout(false);
            pnlProfitability.ResumeLayout(false);
            pnlProfitability.PerformLayout();
            pnlFrozenCapital.ResumeLayout(false);
            pnlFrozenCapital.PerformLayout();
            pnlInventoryHealth.ResumeLayout(false);
            pnlInventoryHealth.PerformLayout();
            pnlCriticos.ResumeLayout(false);
            pnlCriticos.PerformLayout();
            pnlLentos.ResumeLayout(false);
            pnlLentos.PerformLayout();
            pnlBuenos.ResumeLayout(false);
            pnlBuenos.PerformLayout();
            pnlEstrella.ResumeLayout(false);
            pnlEstrella.PerformLayout();
            pnlKPIs.ResumeLayout(false);
            pnlKpiRoi.ResumeLayout(false);
            pnlKpiRoi.PerformLayout();
            pnlKpiGanancia.ResumeLayout(false);
            pnlKpiGanancia.PerformLayout();
            pnlKpiVentas.ResumeLayout(false);
            pnlKpiVentas.PerformLayout();
            pnlKpiInventario.ResumeLayout(false);
            pnlKpiInventario.PerformLayout();
            pnlKpiCapital.ResumeLayout(false);
            pnlKpiCapital.PerformLayout();
            ResumeLayout(false);
        }

        private void ConfigureKpiCard(Panel panel, Label title, Label value, Label delta, Point location, string titleText, string valueText, string deltaText)
        {
            panel.BackColor = Color.White;
            panel.BorderStyle = BorderStyle.FixedSingle;
            panel.Controls.Add(delta);
            panel.Controls.Add(value);
            panel.Controls.Add(title);
            panel.Location = location;
            panel.Name = panel.Name;
            panel.Size = new Size(170, 100);
            title.AutoSize = true;
            title.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            title.ForeColor = Color.FromArgb(113, 128, 150);
            title.Location = new Point(10, 10);
            title.Text = titleText;
            value.AutoSize = true;
            value.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            value.ForeColor = Color.FromArgb(26, 32, 44);
            value.Location = new Point(10, 36);
            value.Text = valueText;
            delta.AutoSize = true;
            delta.Font = new Font("Segoe UI", 8.5F);
            delta.ForeColor = Color.FromArgb(56, 161, 105);
            delta.Location = new Point(10, 72);
            delta.Text = deltaText;
        }

        private void ConfigureStatusCard(Panel panel, Label title, Label value, Point location, string titleText, string valueText)
        {
            panel.BackColor = Color.White;
            panel.BorderStyle = BorderStyle.FixedSingle;
            panel.Controls.Add(value);
            panel.Controls.Add(title);
            panel.Location = location;
            panel.Size = new Size(140, 110);
            title.AutoSize = true;
            title.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            title.Location = new Point(10, 12);
            title.Text = titleText;
            value.AutoSize = true;
            value.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
            value.Location = new Point(10, 48);
            value.Text = valueText;
        }

        #endregion

        private Panel panelScroll;
        private GroupBox pnlKPIs;
        private Panel pnlKpiCapital;
        private Label lblKpiCapTitle;
        private Label lblKpiCapVal;
        private Label lblKpiCapDelta;
        private Panel pnlKpiInventario;
        private Label lblKpiInvTitle;
        private Label lblKpiInvVal;
        private Label lblKpiInvDelta;
        private Panel pnlKpiVentas;
        private Label lblKpiVenTitle;
        private Label lblKpiVenVal;
        private Label lblKpiVenDelta;
        private Panel pnlKpiGanancia;
        private Label lblKpiGanTitle;
        private Label lblKpiGanVal;
        private Label lblKpiGanDelta;
        private Panel pnlKpiRoi;
        private Label lblKpiRoiTitle;
        private Label lblKpiRoiVal;
        private Label lblKpiRoiDelta;
        private GroupBox pnlInventoryHealth;
        private Panel pnlEstrella;
        private Label lblEstrellaTitle;
        private Label lblEstrellaVal;
        private Panel pnlBuenos;
        private Label lblBuenosTitle;
        private Label lblBuenosVal;
        private Panel pnlLentos;
        private Label lblLentosTitle;
        private Label lblLentosVal;
        private Panel pnlCriticos;
        private Label lblCriticosTitle;
        private Label lblCriticosVal;
        private Label lblHealthTitle;
        private Label lblHealthScore;
        private GroupBox pnlFrozenCapital;
        private Label lblFrozenValor;
        private Label lblFrozenPct;
        private Label lblFrozenProductos;
        private Label lblFrozenDias;
        private ProgressBar progressFrozen;
        private Button btnVerDetalleCapital;
        private GroupBox pnlProfitability;
        private Label lblProfitGanancia;
        private Label lblProfitMargen;
        private Label lblProfitRoi;
        private Label lblGanRealizada;
        private Label lblGanPotencial;
        private GroupBox pnlCapital;
        private Label lblCapInvertido;
        private Label lblCapRecuperado;
        private Label lblCapPendiente;
        private Label lblCapInventario;
        private Label lblCapCaja;
        private Panel pnlChartCapital;
        private Label lblChartCapital;
        private GroupBox pnlProducts;
        private Label lblTopTitle;
        private ListBox lstTop;
        private Label lblWatchTitle;
        private ListBox lstWatch;
        private GroupBox pnlTrends;
        private ComboBox cmbTrendMetric;
        private ComboBox cmbTrendPeriod;
        private Panel pnlChartTrends;
        private Label lblChartTrends;
        private GroupBox pnlDecisions;
        private Label lblDecision1;
        private Label lblDecision2;
        private Label lblDecision3;
        private Button btnDecisionVer;
    }
}
